### ISSUE TITLE
general-error=gaierror

### ISSUE THREAD

**Issue by marcsto** [twrecked/pyaarlo#124]
Version: version 0.8.0b8

## Install: 
pip install git+https://github.com/twrecked/pyaarlo

## Code:
import pyaarlo
arlo = pyaarlo.PyArlo( username=USERNAME,password=PASSWORD,
                       tfa_type='SMS',tfa_source='console',synchronous_mode=True, 
                       storage_dir='aarlo')

## Error
general-error=gaierror
Traceback (most recent call last):
  File "D:\code\venv\sunset\lib\site-packages\pyaarlo\backend.py", line 526, in _mqtt_main
    self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
  File "D:\code\venv\sunset\lib\site-packages\paho\mqtt\client.py", line 914, in connect
    return self.reconnect()
  File "D:\code\venv\sunset\lib\site-packages\paho\mqtt\client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "D:\code\venv\sunset\lib\site-packages\paho\mqtt\client.py", line 3685, in _create_socket_connection 
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "C:\Users\marc\AppData\Local\Programs\Python\Python310\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\marc\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo      
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by twrecked** [comment]
Add this to your `PyArlo` command and try again: `backend="sse"`

**Comment by marcsto** [comment]
That worked, thanks!
