### ISSUE TITLE
camera.py line 885: IndentationError: unexpected indent

### ISSUE THREAD

**Issue by mshoe007** [twrecked/pyaarlo#29]
I installed pyaarlo in a python 3.8.2 virtual env and ran 'pyaarlo --help'

mbs-retina:~/src/pyaarlo.venv > pyaarlo --help
Traceback (most recent call last):
  File "/Users/mbs/src/pyaarlo.venv/bin/pyaarlo", line 5, in <module>
    from pyaarlo.main import main_func
  File "/Users/mbs/src/pyaarlo.venv/lib/python3.8/site-packages/pyaarlo/__init__.py", line 12, in <module>
    from .camera import ArloCamera
  File "/Users/mbs/src/pyaarlo.venv/lib/python3.8/site-packages/pyaarlo/camera.py", line 885
    })
    ^
IndentationError: unexpected indent

There appears to be a redundant unmatched '})' at the end of _set_spotlight_properties

I deleted that line, ran again and got an invalid syntax in camera.py line 907 (was 908 before I deleted line 885)

  File "/Users/mbs/src/pyaarlo.venv/lib/python3.8/site-packages/pyaarlo/camera.py", line 907
    'intensity': (brightness / 255 * 100) "      provide an API consistent with nightlight brightness"
                                          ^
SyntaxError: invalid syntax

**Comment by twrecked** [comment]
It was a merge issue, can you try again now.

**Comment by mshoe007** [comment]
Yes, no 'pyaarlo --help' runs without error. Thanks.

**Comment by twrecked** [comment]
Excellent.
