### ISSUE TITLE
camera_stations attribute no longer exists in PyArlo object

### ISSUE THREAD

**Issue by dcline99** [twrecked/pyaarlo#39]
I tried the example in README.md and it failed trying to get the camera_stations attribute.

I dumped the class's __dict__ and grep'd for camera and found this...
 $ grep camera ttt
 '_cameras': [<ArloCamera:camera:BackYard>,
              <ArloCamera:camera:Pool>,
              <ArloCamera:camera:Mailbox>,
              <ArloCamera:camera:FrontDoor>,
              <ArloCamera:camera:Gate>],

Apparently, the attribute is now named _cameras.  Changing the attribute in the example to _cameras instead
of camera_stations allowed it to work properly.  I'm not sure if this is an Arlo change, a class change, or simply
a documentation error.

**Comment by twrecked** [comment]
Sorry, it's a typo/cut-paste error. Try `base.cameras`.

**Comment by Zaschii** [comment]
similar issue with base = arlo.base_stations[0]
.....

[root@edomi arlo]# python3 arlo_baby_alert_aus.py
Traceback (most recent call last):
  File "arlo_baby_alert_aus.py", line 4, in <module>
    tfa_type='SMS',tfa_source='console',synchronous_mode=True)
  File "/usr/local/lib/python3.6/site-packages/pyaarlo/__init__.py", line 210, in __init__
    self._refresh_bases(initial=True)
  File "/usr/local/lib/python3.6/site-packages/pyaarlo/__init__.py", line 278, in _refresh_bases
    base.update_modes()
  File "/usr/local/lib/python3.6/site-packages/pyaarlo/base.py", line 251, in update_modes
    props = resp.get('properties', {})
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by twrecked** [comment]
@Zaschii does your Arlo account have admin access?
