### ISSUE TITLE
AttributeError: 'ArloBase' object has no attribute 'update_resources'

### ISSUE THREAD

**Issue by pfmos** [twrecked/pyaarlo#82]
Aarlo integration appears to be working but seeing this error in my core logs:

2021-12-11 05:21:10 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 05:34:01 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 05:39:17 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 05:41:48 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next
    job["callback"](**job["args"])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 306, in _refresh_devices
    base.update_resources(props)
AttributeError: 'ArloBase' object has no attribute 'update_resources'

2021-12-11 05:42:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-12-11 05:45:02 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 05:52:56 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 05:58:10 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:01:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-12-11 06:03:36 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:09:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:15:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:22:03 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:28:25 ERROR (Thread-14) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:34:10 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:39:36 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:41:48 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next
    job["callback"](**job["args"])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 306, in _refresh_devices
    base.update_resources(props)
AttributeError: 'ArloBase' object has no attribute 'update_resources'

2021-12-11 06:45:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:51:28 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 06:58:36 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:07:16 ERROR (MainThread) [aioharmony.hubconnector_websocket] 192.168.1.23: Connection timed out for hub 8657110
2021-12-11 07:09:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:21:31 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:28:03 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:33:36 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:42:48 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next
    job["callback"](**job["args"])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 306, in _refresh_devices
    base.update_resources(props)
AttributeError: 'ArloBase' object has no attribute 'update_resources'

2021-12-11 07:46:17 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 07:52:17 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:03:17 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:09:35 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:15:05 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:21:07 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:26:56 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:33:06 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:39:07 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2021-12-11 08:43:48 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next
    job["callback"](**job["args"])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 306, in _refresh_devices
    base.update_resources(props)
AttributeError: 'ArloBase' object has no attribute 'update_resources'

2021-12-11 08:45:36 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[finish] process exit code 0
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by twrecked** [comment]
I'll push a fix for it.

**Comment by twrecked** [comment]
Should be fixed in b4.

**Comment by pfmos** [comment]
Thank you!
